### PR TITLE
Fix js bundling

### PR DESCRIPTION
**Pull request by obuchtala**
- Streamlined bundling
- changed npm library name `stencila-mini-core -> stencila-libcore` :
  - less dashes
  - removed 'mini' from name, as it is now a pure library, which can be used outside mini as well

### CODE REVIEW

**Comment by obuchtala** [comment]
@nokome are you ok with the renaming?

**Comment by michael** [comment]
stencila-libcore is not yet published on npm. @oliver---- can I?

**Comment by nokome** [comment]
I'm about to review this PR and will then publish. Give me 30mins. I'll ping you :)

**Comment by michael** [comment]
Oh looks like stencila-libcore is not yet referenced in Stencila. So better wait?

**Comment by nokome** [comment]
@oliver---- : thanks for this :+1: 

Yes, the renaming is the right thing to do! I've completed that process, will rename this repo, publish to  npm, and deprecate `mini-core`.

Also made some fixes to bundling for tests.

**Pull request merged**
